### ISSUE TITLE
rake db:migrate で pg がエラーを起こします。

### ISSUE THREAD

**Issue by marphy986** [LGDIS/LGDIS#8]
```
marphy-MacBookPro:LGDIS marphy$ ruby -v
ruby 1.9.3p392 (2013-02-22 revision 39386) [x86_64-darwin12.2.0]
marphy-MacBookPro:LGDIS marphy$ 
marphy-MacBookPro:LGDIS marphy$ git pull
Already up-to-date.
marphy-MacBookPro:LGDIS marphy$ 
marphy-MacBookPro:LGDIS marphy$ 
marphy-MacBookPro:LGDIS marphy$ rake db:drop
NOTICE:  database "LGDIS_dev" does not exist, skipping
NOTICE:  database "LGDIS_test" does not exist, skipping
marphy-MacBookPro:LGDIS marphy$ rake db:create
marphy-MacBookPro:LGDIS marphy$ rake db:migrate
rake aborted!
PG::Error: ERROR:  relation "constants" does not exist
LINE 5:              WHERE a.attrelid = '"constants"'::regclass
                                        ^
:             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
              FROM pg_attribute a LEFT JOIN pg_attrdef d
                ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = '"constants"'::regclass
               AND a.attnum > 0 AND NOT a.attisdropped
             ORDER BY a.attnum
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1153:in `async_exec'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1153:in `exec_no_cache'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:662:in `block in exec_query'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `exec_query'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1278:in `column_definitions'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:857:in `columns'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/connection_adapters/schema_cache.rb:12:in `block in initialize'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:228:in `yield'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:228:in `default'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:228:in `columns'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:237:in `columns_hash'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/locking/optimistic.rb:129:in `locking_enabled?'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/relation.rb:170:in `exec_queries'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/relation.rb:160:in `block in to_a'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/explain.rb:40:in `logging_query_plan'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/relation.rb:159:in `to_a'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/relation/finder_methods.rb:159:in `all'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/relation/finder_methods.rb:105:in `find'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/relation/finder_methods.rb:101:in `find'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activerecord-3.2.12/lib/active_record/querying.rb:5:in `find'
/Users/marphy/Rails/LGDIS/plugins/lgdis/app/models/constant.rb:13:in `hash_for_table'
/Users/marphy/Rails/LGDIS/plugins/lgdis/lib/lgdis/issue_patch.rb:81:in `<module:InstanceMethods>'
/Users/marphy/Rails/LGDIS/plugins/lgdis/lib/lgdis/issue_patch.rb:74:in `<module:IssuePatch>'
/Users/marphy/Rails/LGDIS/plugins/lgdis/lib/lgdis/issue_patch.rb:6:in `<module:Lgdis>'
/Users/marphy/Rails/LGDIS/plugins/lgdis/lib/lgdis/issue_patch.rb:5:in `<top (required)>'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:469:in `load'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:469:in `block in load_file'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:639:in `new_constants_in'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:468:in `load_file'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:353:in `require_or_load'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:313:in `depend_on'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:225:in `require_dependency'
/Users/marphy/Rails/LGDIS/plugins/lgdis/init.rb:34:in `<top (required)>'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/marphy/Rails/LGDIS/lib/redmine/plugin.rb:130:in `block in load'
/Users/marphy/Rails/LGDIS/lib/redmine/plugin.rb:121:in `each'
/Users/marphy/Rails/LGDIS/lib/redmine/plugin.rb:121:in `load'
/Users/marphy/Rails/LGDIS/config/initializers/30-redmine.rb:12:in `<top (required)>'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `load'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `block in load'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `load'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.12/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.12/lib/rails/engine.rb:587:in `each'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.12/lib/rails/engine.rb:587:in `block in <class:Engine>'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.12/lib/rails/initializable.rb:30:in `instance_exec'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.12/lib/rails/initializable.rb:30:in `run'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.12/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.12/lib/rails/initializable.rb:54:in `each'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.12/lib/rails/initializable.rb:54:in `run_initializers'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.12/lib/rails/application.rb:136:in `initialize!'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/marphy/Rails/LGDIS/config/environment.rb:14:in `<top (required)>'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.12/lib/rails/application.rb:103:in `require_environment!'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.12/lib/rails/application.rb:297:in `block (2 levels) in initialize_tasks'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
marphy-MacBookPro:LGDIS marphy$ 
```

**Comment by marphy986** [comment]
何となく再現しなくなりました。
