### ISSUE TITLE
rake db:migrate でエラーを起こします。

### ISSUE THREAD

**Issue by marphy986** [LGDIS/LGDIS#9]
```
marphy-MacBookPro:LGDIS marphy$ rvm use 1.9.3
Using /Users/marphy/.rvm/gems/ruby-1.9.3-p392
marphy-MacBookPro:LGDIS marphy$ bundle update
Updating git://github.com/ruvr/omniauth-saml.git
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Using rake (10.0.3) 
Using i18n (0.6.4) 
Using multi_json (1.6.1) 
Using activesupport (3.2.11) 
Using builder (3.0.0) 
Using activemodel (3.2.11) 
Using erubis (2.7.0) 
Using journey (1.0.4) 
Using rack (1.4.5) 
Using rack-cache (1.2) 
Using rack-test (0.6.2) 
Using hike (1.2.1) 
Using tilt (1.3.4) 
Using sprockets (2.2.2) 
Using actionpack (3.2.11) 
Using mime-types (1.21) 
Using polyglot (0.3.3) 
Using treetop (1.4.12) 
Using mail (2.4.4) 
Using actionmailer (3.2.11) 
Using arel (3.0.2) 
Using tzinfo (0.3.35) 
Using activerecord (3.2.11) 
Using activeresource (3.2.11) 
Using acts_as_paranoid (0.4.1) 
Using addressable (2.3.3) 
Using gyoku (1.0.0) 
Using nokogiri (1.5.6) 
Using akami (1.2.0) 
Using bundler (1.3.0) 
Using canonix (0.1.1) 
Using coderay (1.0.9) 
Using diff-lcs (1.2.1) 
Using factory_girl (4.2.0) 
Using rack-ssl (1.3.3) 
Using json (1.7.7) 
Using rdoc (3.12.2) 
Using thor (0.17.0) 
Using railties (3.2.11) 
Using factory_girl_rails (4.2.1) 
Using multipart-post (1.2.0) 
Using faraday (0.8.6) 
Using hashie (1.2.0) 
Using httpauth (0.2.0) 
Using httpi (2.0.2) 
Using jpmobile (3.0.7) 
Using jquery-rails (2.0.3) 
Using jwt (0.1.5) 
Using koala (1.6.0) 
Using systemu (2.5.2) 
Using macaddr (1.6.1) 
Using polyamorous (0.5.0) 
Using meta_search (1.1.3) 
Using metaclass (0.0.1) 
Using mocha (0.12.3) 
Using mysql2 (0.3.11) 
Using net-ldap (0.3.1) 
Using nori (2.0.4) 
Using oauth (0.4.7) 
Using oauth2 (0.8.1) 
Using omniauth (1.1.3) 
Using omniauth-oauth2 (1.1.1) 
Using omniauth-facebook (1.4.1) 
Using omniauth-oauth (1.0.1) 
Using ruby-openid (2.1.8) 
Using rack-openid (1.3.1) 
Using omniauth-openid (1.0.1) 
Using uuid (2.3.7) 
Using ruby-saml (0.7.2) 
Using omniauth-saml (1.0.0) from git://github.com/ruvr/omniauth-saml.git (at master) 
Using omniauth-twitter (0.0.14) 
Using pg (0.14.1) 
Using rails (3.2.11) 
Using rspec-core (2.13.0) 
Using rspec-expectations (2.13.0) 
Using rspec-mocks (2.13.0) 
Using rspec-rails (2.13.0) 
Using pg_power (1.3.0) 
Using rack-protection (1.4.0) 
Installing redis (3.0.3) 
Using redis-namespace (1.2.1) 
Using sinatra (1.3.5) 
Using vegas (0.1.11) 
Using resque (1.23.0) 
Using rmagick (2.13.2) 
Using rspec (2.13.0) 
Using wasabi (3.0.0) 
Using savon (2.1.0) 
Using shoulda (2.11.3) 
Using simple_oauth (0.2.0) 
Using soap4r-ruby1.9 (2.0.5) 
Using sqlite3 (1.3.7) 
Using test-unit (2.5.4) 
Using twitter (4.5.0) 
Using uuidtools (2.1.3) 
Using will_paginate (3.0.4) 
Using yard (0.8.5.2) 
Your bundle is updated! Use `bundle show [gemname]` to see where a bundled gem is installed.
marphy-MacBookPro:LGDIS marphy$ rake db:drop
marphy-MacBookPro:LGDIS marphy$ rake db:create
marphy-MacBookPro:LGDIS marphy$ rake db:migrate
rake aborted!
undefined method `[]' for nil:NilClass
/Users/marphy/Rails/LGDIS/plugins/lgdis/config/initializers/omniauth.rb:12:in `block in <top (required)>'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/omniauth-1.1.3/lib/omniauth/builder.rb:7:in `initialize'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/actionpack-3.2.11/lib/action_dispatch/middleware/stack.rb:43:in `new'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/actionpack-3.2.11/lib/action_dispatch/middleware/stack.rb:43:in `build'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/actionpack-3.2.11/lib/action_dispatch/middleware/stack.rb:113:in `block in build'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/actionpack-3.2.11/lib/action_dispatch/middleware/stack.rb:113:in `each'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/actionpack-3.2.11/lib/action_dispatch/middleware/stack.rb:113:in `inject'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/actionpack-3.2.11/lib/action_dispatch/middleware/stack.rb:113:in `build'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.11/lib/rails/engine.rb:470:in `app'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.11/lib/rails/application/finisher.rb:31:in `block in <module:Finisher>'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `instance_exec'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `run'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `each'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `run_initializers'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.11/lib/rails/application.rb:136:in `initialize!'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/marphy/Rails/LGDIS/config/environment.rb:14:in `<top (required)>'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.11/lib/rails/application.rb:103:in `require_environment!'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.11/lib/rails/application.rb:297:in `block (2 levels) in initialize_tasks'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
/Users/marphy/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
marphy-MacBookPro:LGDIS marphy$ 
```

**Comment by c-yasuda** [comment]
plugins/lgdis/config/api_key.ymlがexampleに追従できていない事が原因でした。
修正致しましたので、ご確認お願いします。

**Comment by marphy986** [comment]
動きました。

出来上がったあかつきには plugins/lgdis/config/api_key.yml は .gitignore にしなければならないでしょうね。
そちらで支障がないなら、今は repo に含めてていいと思います。
